twig:
    file_name_pattern: '*.twig'
    paths: 
        - '%kernel.project_dir%/vendor/symfony/twig-bridge/Resources/views/Form/'
        - '%kernel.project_dir%/templates/'
    form_themes: 
        - 'form/tailwind_4_layout.html.twig'

when@test:
    twig:
        strict_variables: true
